// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class WATypesBytes;
@class WATypesField;
@class WATypesPointer;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WATypesTypesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface WATypesTypesRoot : GPBRootObject
@end

#pragma mark - WATypesImage

typedef GPB_ENUM(WATypesImage_FieldNumber) {
  WATypesImage_FieldNumber_URL = 1,
  WATypesImage_FieldNumber_Data_p = 2,
  WATypesImage_FieldNumber_Metadata = 3,
};

GPB_FINAL @interface WATypesImage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

/** base64 data */
@property(nonatomic, readwrite, strong, null_resettable) WATypesBytes *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

/** blur, mime */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

@end

#pragma mark - WATypesBytes

typedef GPB_ENUM(WATypesBytes_FieldNumber) {
  WATypesBytes_FieldNumber_Raw = 1,
  WATypesBytes_FieldNumber_Ptr = 2,
};

typedef GPB_ENUM(WATypesBytes_Data_OneOfCase) {
  WATypesBytes_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  WATypesBytes_Data_OneOfCase_Raw = 1,
  WATypesBytes_Data_OneOfCase_Ptr = 2,
};

GPB_FINAL @interface WATypesBytes : GPBMessage

@property(nonatomic, readonly) WATypesBytes_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSData *raw;

@property(nonatomic, readwrite, strong, null_resettable) WATypesPointer *ptr;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void WATypesBytes_ClearDataOneOfCase(WATypesBytes *message);

#pragma mark - WATypesPointer

typedef GPB_ENUM(WATypesPointer_FieldNumber) {
  WATypesPointer_FieldNumber_Ptr = 1,
  WATypesPointer_FieldNumber_Len = 2,
};

GPB_FINAL @interface WATypesPointer : GPBMessage

@property(nonatomic, readwrite) uint32_t ptr;

@property(nonatomic, readwrite) uint32_t len;

@end

#pragma mark - WATypesString

typedef GPB_ENUM(WATypesString_FieldNumber) {
  WATypesString_FieldNumber_Raw = 1,
  WATypesString_FieldNumber_Ptr = 2,
};

typedef GPB_ENUM(WATypesString_Data_OneOfCase) {
  WATypesString_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  WATypesString_Data_OneOfCase_Raw = 1,
  WATypesString_Data_OneOfCase_Ptr = 2,
};

GPB_FINAL @interface WATypesString : GPBMessage

@property(nonatomic, readonly) WATypesString_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *raw;

@property(nonatomic, readwrite, strong, null_resettable) WATypesPointer *ptr;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void WATypesString_ClearDataOneOfCase(WATypesString *message);

#pragma mark - WATypesVoid

GPB_FINAL @interface WATypesVoid : GPBMessage

@end

#pragma mark - WATypesError

typedef GPB_ENUM(WATypesError_FieldNumber) {
  WATypesError_FieldNumber_Code = 1,
  WATypesError_FieldNumber_Reason = 2,
};

GPB_FINAL @interface WATypesError : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - WATypesWAFuture

typedef GPB_ENUM(WATypesWAFuture_FieldNumber) {
  WATypesWAFuture_FieldNumber_Data_p = 1,
  WATypesWAFuture_FieldNumber_Len = 2,
  WATypesWAFuture_FieldNumber_Callback = 3,
  WATypesWAFuture_FieldNumber_Context = 4,
  WATypesWAFuture_FieldNumber_ContextLen = 5,
  WATypesWAFuture_FieldNumber_Index = 6,
};

GPB_FINAL @interface WATypesWAFuture : GPBMessage

@property(nonatomic, readwrite) uint32_t data_p;

@property(nonatomic, readwrite) uint32_t len;

@property(nonatomic, readwrite) uint32_t callback;

@property(nonatomic, readwrite) uint32_t context;

@property(nonatomic, readwrite) uint32_t contextLen;

@property(nonatomic, readwrite) uint32_t index;

@end

#pragma mark - WATypesWAString

typedef GPB_ENUM(WATypesWAString_FieldNumber) {
  WATypesWAString_FieldNumber_Ptr = 1,
  WATypesWAString_FieldNumber_Len = 2,
};

GPB_FINAL @interface WATypesWAString : GPBMessage

@property(nonatomic, readwrite) uint32_t ptr;

@property(nonatomic, readwrite) uint32_t len;

@end

#pragma mark - WATypesField

typedef GPB_ENUM(WATypesField_FieldNumber) {
  WATypesField_FieldNumber_Type = 1,
  WATypesField_FieldNumber_Value = 2,
};

GPB_FINAL @interface WATypesField : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - WATypesEntry

typedef GPB_ENUM(WATypesEntry_FieldNumber) {
  WATypesEntry_FieldNumber_Id_p = 1,
  WATypesEntry_FieldNumber_Name = 2,
  WATypesEntry_FieldNumber_Desc = 3,
  WATypesEntry_FieldNumber_Field = 4,
  WATypesEntry_FieldNumber_Validator = 5,
};

GPB_FINAL @interface WATypesEntry : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@property(nonatomic, readwrite, strong, null_resettable) WATypesField *field;
/** Test to see if @c field has been set. */
@property(nonatomic, readwrite) BOOL hasField;

@property(nonatomic, readwrite, copy, null_resettable) NSString *validator;
/** Test to see if @c validator has been set. */
@property(nonatomic, readwrite) BOOL hasValidator;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
