// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TypesBytes;
@class TypesPointer;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TypesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TypesRoot : GPBRootObject
@end

#pragma mark - TypesImage

typedef GPB_ENUM(TypesImage_FieldNumber) {
  TypesImage_FieldNumber_URL = 1,
  TypesImage_FieldNumber_Data_p = 2,
  TypesImage_FieldNumber_Width = 3,
  TypesImage_FieldNumber_Height = 4,
};

GPB_FINAL @interface TypesImage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

/** base64 data */
@property(nonatomic, readwrite, strong, null_resettable) TypesBytes *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) double width;
@property(nonatomic, readwrite) BOOL hasWidth;

@property(nonatomic, readwrite) double height;
@property(nonatomic, readwrite) BOOL hasHeight;

@end

#pragma mark - TypesBytes

typedef GPB_ENUM(TypesBytes_FieldNumber) {
  TypesBytes_FieldNumber_Raw = 1,
  TypesBytes_FieldNumber_Ptr = 2,
};

typedef GPB_ENUM(TypesBytes_Data_OneOfCase) {
  TypesBytes_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  TypesBytes_Data_OneOfCase_Raw = 1,
  TypesBytes_Data_OneOfCase_Ptr = 2,
};

GPB_FINAL @interface TypesBytes : GPBMessage

@property(nonatomic, readonly) TypesBytes_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSData *raw;

@property(nonatomic, readwrite, strong, null_resettable) TypesPointer *ptr;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void TypesBytes_ClearDataOneOfCase(TypesBytes *message);

#pragma mark - TypesPointer

typedef GPB_ENUM(TypesPointer_FieldNumber) {
  TypesPointer_FieldNumber_Ptr = 1,
  TypesPointer_FieldNumber_Len = 2,
};

GPB_FINAL @interface TypesPointer : GPBMessage

@property(nonatomic, readwrite) uint32_t ptr;

@property(nonatomic, readwrite) uint32_t len;

@end

#pragma mark - TypesString

typedef GPB_ENUM(TypesString_FieldNumber) {
  TypesString_FieldNumber_Raw = 1,
  TypesString_FieldNumber_Ptr = 2,
};

typedef GPB_ENUM(TypesString_Data_OneOfCase) {
  TypesString_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  TypesString_Data_OneOfCase_Raw = 1,
  TypesString_Data_OneOfCase_Ptr = 2,
};

GPB_FINAL @interface TypesString : GPBMessage

@property(nonatomic, readonly) TypesString_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *raw;

@property(nonatomic, readwrite, strong, null_resettable) TypesPointer *ptr;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void TypesString_ClearDataOneOfCase(TypesString *message);

#pragma mark - TypesVoid

GPB_FINAL @interface TypesVoid : GPBMessage

@end

#pragma mark - TypesError

typedef GPB_ENUM(TypesError_FieldNumber) {
  TypesError_FieldNumber_Code = 1,
  TypesError_FieldNumber_Reason = 2,
};

GPB_FINAL @interface TypesError : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - TypesWAFuture

typedef GPB_ENUM(TypesWAFuture_FieldNumber) {
  TypesWAFuture_FieldNumber_Data_p = 1,
  TypesWAFuture_FieldNumber_Len = 2,
  TypesWAFuture_FieldNumber_Callback = 3,
  TypesWAFuture_FieldNumber_Context = 4,
  TypesWAFuture_FieldNumber_ContextLen = 5,
  TypesWAFuture_FieldNumber_Index = 6,
};

GPB_FINAL @interface TypesWAFuture : GPBMessage

@property(nonatomic, readwrite) uint32_t data_p;

@property(nonatomic, readwrite) uint32_t len;

@property(nonatomic, readwrite) uint32_t callback;

@property(nonatomic, readwrite) uint32_t context;

@property(nonatomic, readwrite) uint32_t contextLen;

@property(nonatomic, readwrite) uint32_t index;

@end

#pragma mark - TypesWAString

typedef GPB_ENUM(TypesWAString_FieldNumber) {
  TypesWAString_FieldNumber_Ptr = 1,
  TypesWAString_FieldNumber_Len = 2,
};

GPB_FINAL @interface TypesWAString : GPBMessage

@property(nonatomic, readwrite) uint32_t ptr;

@property(nonatomic, readwrite) uint32_t len;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
