// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: music.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MusicAuthor;
@class MusicEntry;
@class MusicListOptions_Discover;
@class MusicListOptions_Search;
@class MusicTrack;
@class MusicTrackDetails_Format;
@class MusicTranscript_Segment;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MusicCallID

typedef GPB_ENUM(MusicCallID) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MusicCallID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MusicCallID_CallIdUnspecified = 0,
  MusicCallID_CallIdGetDetails = 1,
  MusicCallID_CallIdGetPlaylistDetails = 2,
  MusicCallID_CallIdSearch = 3,
  MusicCallID_CallIdSuggestion = 4,
  MusicCallID_CallIdGetOptions = 5,
  MusicCallID_CallIdGetDiscover = 6,
  MusicCallID_CallIdGetTranscript = 7,
};

GPBEnumDescriptor *MusicCallID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MusicCallID_IsValidValue(int32_t value);

#pragma mark - MusicRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MusicRoot : GPBRootObject
@end

#pragma mark - MusicOptions

typedef GPB_ENUM(MusicOptions_FieldNumber) {
  MusicOptions_FieldNumber_Provider = 1,
};

GPB_FINAL @interface MusicOptions : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *provider;

@end

#pragma mark - MusicListOptions

typedef GPB_ENUM(MusicListOptions_FieldNumber) {
  MusicListOptions_FieldNumber_ProvidersArray = 1,
  MusicListOptions_FieldNumber_Discover = 2,
  MusicListOptions_FieldNumber_Search = 3,
};

GPB_FINAL @interface MusicListOptions : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicEntry*> *providersArray;
/** The number of items in @c providersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger providersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) MusicListOptions_Discover *discover;
/** Test to see if @c discover has been set. */
@property(nonatomic, readwrite) BOOL hasDiscover;

@property(nonatomic, readwrite, strong, null_resettable) MusicListOptions_Search *search;
/** Test to see if @c search has been set. */
@property(nonatomic, readwrite) BOOL hasSearch;

@end

#pragma mark - MusicListOptions_Discover

typedef GPB_ENUM(MusicListOptions_Discover_FieldNumber) {
  MusicListOptions_Discover_FieldNumber_CategoriesArray = 1,
};

GPB_FINAL @interface MusicListOptions_Discover : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicEntry*> *categoriesArray;
/** The number of items in @c categoriesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger categoriesArray_Count;

@end

#pragma mark - MusicListOptions_Search

typedef GPB_ENUM(MusicListOptions_Search_FieldNumber) {
  MusicListOptions_Search_FieldNumber_ScopesArray = 1,
};

GPB_FINAL @interface MusicListOptions_Search : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *scopesArray;
/** The number of items in @c scopesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger scopesArray_Count;

@end

#pragma mark - MusicEntry

typedef GPB_ENUM(MusicEntry_FieldNumber) {
  MusicEntry_FieldNumber_Id_p = 1,
  MusicEntry_FieldNumber_Name = 2,
};

GPB_FINAL @interface MusicEntry : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - MusicTrackDetails

typedef GPB_ENUM(MusicTrackDetails_FieldNumber) {
  MusicTrackDetails_FieldNumber_Id_p = 1,
  MusicTrackDetails_FieldNumber_Title = 2,
  MusicTrackDetails_FieldNumber_Description_p = 3,
  MusicTrackDetails_FieldNumber_Author = 4,
  MusicTrackDetails_FieldNumber_FormatsArray = 5,
  MusicTrackDetails_FieldNumber_Thumbnail = 6,
  MusicTrackDetails_FieldNumber_Duration = 7,
  MusicTrackDetails_FieldNumber_Views = 8,
  MusicTrackDetails_FieldNumber_DashManifestURL = 9,
  MusicTrackDetails_FieldNumber_HlsManifestURL = 10,
  MusicTrackDetails_FieldNumber_RelatedTracksArray = 11,
};

GPB_FINAL @interface MusicTrackDetails : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, strong, null_resettable) MusicAuthor *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicTrackDetails_Format*> *formatsArray;
/** The number of items in @c formatsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger formatsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@property(nonatomic, readwrite) double duration;

@property(nonatomic, readwrite) int32_t views;

@property(nonatomic, readwrite, copy, null_resettable) NSString *dashManifestURL;
/** Test to see if @c dashManifestURL has been set. */
@property(nonatomic, readwrite) BOOL hasDashManifestURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hlsManifestURL;
/** Test to see if @c hlsManifestURL has been set. */
@property(nonatomic, readwrite) BOOL hasHlsManifestURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicTrack*> *relatedTracksArray;
/** The number of items in @c relatedTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger relatedTracksArray_Count;

@end

#pragma mark - MusicTrackDetails_Format

typedef GPB_ENUM(MusicTrackDetails_Format_FieldNumber) {
  MusicTrackDetails_Format_FieldNumber_Id_p = 1,
  MusicTrackDetails_Format_FieldNumber_URL = 2,
  MusicTrackDetails_Format_FieldNumber_Quality = 3,
  MusicTrackDetails_Format_FieldNumber_Metadata = 4,
};

GPB_FINAL @interface MusicTrackDetails_Format : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quality;
/** Test to see if @c quality has been set. */
@property(nonatomic, readwrite) BOOL hasQuality;

@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

@end

#pragma mark - MusicTranscript

typedef GPB_ENUM(MusicTranscript_FieldNumber) {
  MusicTranscript_FieldNumber_SegmentsArray = 1,
};

GPB_FINAL @interface MusicTranscript : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicTranscript_Segment*> *segmentsArray;
/** The number of items in @c segmentsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger segmentsArray_Count;

@end

#pragma mark - MusicTranscript_Segment

typedef GPB_ENUM(MusicTranscript_Segment_FieldNumber) {
  MusicTranscript_Segment_FieldNumber_Text = 1,
  MusicTranscript_Segment_FieldNumber_Offset = 2,
  MusicTranscript_Segment_FieldNumber_Duration = 3,
};

GPB_FINAL @interface MusicTranscript_Segment : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite) int32_t duration;

@end

#pragma mark - MusicAuthor

typedef GPB_ENUM(MusicAuthor_FieldNumber) {
  MusicAuthor_FieldNumber_Id_p = 1,
  MusicAuthor_FieldNumber_Name = 2,
  MusicAuthor_FieldNumber_Thumbnail = 3,
};

GPB_FINAL @interface MusicAuthor : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@end

#pragma mark - MusicTrack

typedef GPB_ENUM(MusicTrack_FieldNumber) {
  MusicTrack_FieldNumber_Id_p = 1,
  MusicTrack_FieldNumber_Title = 2,
  MusicTrack_FieldNumber_Kind = 3,
  MusicTrack_FieldNumber_Author = 4,
  MusicTrack_FieldNumber_Thumbnail = 5,
};

GPB_FINAL @interface MusicTrack : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *kind;

@property(nonatomic, readwrite, strong, null_resettable) MusicAuthor *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@end

#pragma mark - MusicListTracks

typedef GPB_ENUM(MusicListTracks_FieldNumber) {
  MusicListTracks_FieldNumber_ItemsArray = 1,
  MusicListTracks_FieldNumber_Continuation = 2,
};

GPB_FINAL @interface MusicListTracks : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MusicTrack*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *continuation;
/** Test to see if @c continuation has been set. */
@property(nonatomic, readwrite) BOOL hasContinuation;

@end

#pragma mark - MusicListSuggestions

typedef GPB_ENUM(MusicListSuggestions_FieldNumber) {
  MusicListSuggestions_FieldNumber_SuggestionsArray = 1,
};

GPB_FINAL @interface MusicListSuggestions : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *suggestionsArray;
/** The number of items in @c suggestionsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger suggestionsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
